### ISSUE TITLE
Inconsistent behavior with RData files

### ISSUE THREAD

**Issue by hliebert** [chainsawriot/rio#295]
I've stumbled upon some strange behavior today when comparing rio with the builtin load/save. I presume the first part where the object is not imported in the global environment is intentional. Is the second part related?

```R
rio::export(iris, "test.RData")
save(iris, file = "test2.RData")

rio::import("test.RData") # doesn't actually import iris
load("test2.RData")       # imports iris

rm(iris)

load("test.RData")  # is named x
load("test2.RData") # is named iris
```

**Comment by chainsawriot** [comment]
@hliebert Thank you for reporting this. This behavior is intention because `rio::import()` always returns a data frame. Rather than the side-effect of putting sometime to the current global environment.

The intended way to use `rio::import()` for .RData is like this (not very different from `.RDS`):

```r
tempRdata <- tempfile(fileext = ".RData")
rio::export(iris, tempRdata)
newdata <- rio::import(tempRdata)
newdata
```
