### ISSUE TITLE
Add option to send import_list results directly to the environment

### ISSUE THREAD

**Issue by NickCH-K** [chainsawriot/rio#299]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Hi there, loving the package! I switched everything over to it like ten minutes after trying it out and it works great.

I think it would be handy to have an option in `import_list()` to send the results directly to the environment, rather than to a list. This would be most relevant when importing the sheets of an Excel file, which you'd commonly want to treat as entirely separate objects. However, I can also imagine it being useful when importing a series of files that happen to be entirely different (i.e. you wouldn't want to `rbindlist()` them anyway).

This would be very easy to implement. Simply having the option run `list2env(x, envir = parent.frame())` on the results of `import_list()`, rather than returning `x`, would do the trick. You could also add some steps to edit the list names first so you don't end up with objects with spaces etc. in the name (and/or allow a vector of object names).

Put your code here:

```R
## load package
library("rio")

## code goes here
## example.xlsx is an Excel workbook with the sheets Data, Dictionary, and Departments
## Current approach
dlist = import_list('example.xlsx')
Data = dlist[[1]]
Dictionary = dlist[[2]]
Departments = dlist[[3]]
rm(dlist)

## Desired approach
import_list('example.xlsx', to_environment = TRUE)
# or perhaps name it "load" to mimic load()?
```

**Comment by chainsawriot** [comment]
@NickCH-K Thank you very much for suggesting this. However, this substantially changes the promise that `import_list()` as a pure function should always return something, i.e. it should not work like `load()`. The side effect of silently injecting objects to the `parent.frame()` can also be a big source of errors, e.g. how duplicated names in a zip archive should be handled; how to communicate back to the user on the modified named objects injected to the current environment. Some would also complain this "pollute" the current environment.

```r
a <- "apple"
list("a" = "aeroplane", "b" = "bee") |> list2env(envir = parent.frame()) # no warning, no error
print(a)
```

(The outcome also depends on how `parent.frame()` is interpreted by R and in what environment the code is running. `reprex::reprex()` for instance, `a` is still "apple").

I would argue that one should run `list2env()` manually for this, so that one knows what's the possible consequences.
